$ErrorActionPreference = "Stop"

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) {
        throw $Message
    }
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$SourcePath = Join-Path $RepoRoot "cppmods\MecchaCamouflage\src\dllmain.cpp"
$SourceText = Get-Content -Raw $SourcePath
$CoreFiles = Get-ChildItem (Join-Path $RepoRoot "cppmods\MecchaCamouflage\include\MecchaCamouflage\core"), (Join-Path $RepoRoot "cppmods\MecchaCamouflage\src\core") -Recurse -File
$CoreText = ($CoreFiles | ForEach-Object { Get-Content -Raw $_.FullName }) -join "`n"

Assert-True ($SourceText.Contains("route=f10_v2_runtime_atlas")) "F10 V2 runtime atlas route marker is missing"
Assert-True ($SourceText.Contains("backend=tick_bounded_runtime_probe")) "V2 tick-bounded backend marker is missing"
Assert-True ($SourceText.Contains("legacy_splat_success=0")) "legacy splat refusal marker is missing"
Assert-True ($SourceText.Contains("fallback_used=0")) "fallback disabled marker is missing"
Assert-True (-not $SourceText.Contains("auto run_play() -> void")) "synchronous run_play route remains"
Assert-True (-not $SourceText.Contains("run_play();")) "F10 path still calls synchronous run_play"
Assert-True ($SourceText.Contains("execute_pipeline_once")) "pipeline execution coordinator is missing"
Assert-True ($SourceText.Contains("start_pipeline_job")) "tick-driven pipeline start is missing"
Assert-True ($SourceText.Contains("advance_pipeline_job")) "tick-driven pipeline advance is missing"
Assert-True ($SourceText.Contains("refined_hit_tick")) "refined hit tick progress marker is missing"
Assert-True ($SourceText.Contains("deferred_cache_used=1")) "deferred refined cache marker is missing"
Assert-True ($SourceText.Contains("UiPipelineStage::Preflight")) "V2 preflight stage is missing"
Assert-True ($SourceText.Contains("UiPipelineStage::AtlasProbe")) "V2 atlas probe stage is missing"
Assert-True ($SourceText.Contains("UiPipelineStage::SurfaceTraceSampling")) "V2 surface sampling stage is missing"
Assert-True ($SourceText.Contains("probe_v2_runtime_capabilities")) "V2 runtime capability probe is missing"
Assert-True ($SourceText.Contains("probe_v2_runtime_atlas")) "V2 runtime atlas probe is missing"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::validate_capture_quality")) "core capture validation is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::assemble_direct_texture")) "core texture assembly is not used"
Assert-True ($CoreText.Contains("assemble_chart_aware_texture")) "core chart-aware texture assembly is missing"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::is_floor_like_label")) "core floor-like classifier is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::resolve_material_channels")) "core material resolver is not used"
Assert-True ($CoreText.Contains("resolve_verified_material_evidence")) "core verified material evidence resolver is missing"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::chroma_distance_rgb")) "runtime chroma validation does not use core metric"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::choose_capture_dimensions")) "adaptive capture sizing policy is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::choose_adaptive_sampling_policy")) "adaptive sampling policy is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::generate_golden_angle_views")) "golden-angle side views are not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::evaluate_uv_coverage")) "UV coverage gate is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::evaluate_runtime_atlas_probe")) "runtime atlas probe gate is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::evaluate_atlas_coverage")) "atlas coverage gate is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::choose_apply_backend")) "apply backend gate is not used"
Assert-True ($SourceText.Contains("MecchaCamouflage::Core::estimate_seed_radius_for_density")) "density-based seed radius is not used"
Assert-True (-not $SourceText.Contains("ProjectionCaptureResolution")) "fixed projection capture cap remains"
Assert-True ($SourceText.Contains("capability_probe route=f10_v2_runtime_atlas")) "V2 capability probe marker is missing"
Assert-True ($SourceText.Contains("server_paint_api")) "replicated paint API capability marker is missing"
Assert-True ($SourceText.Contains("multicast_paint_api")) "multicast paint API capability marker is missing"
Assert-True ($SourceText.Contains("replicated_paint_function")) "replicated paint function struct diagnostic marker is missing"
Assert-True ($SourceText.Contains("capture_resolution_source=")) "capture resolution source marker is missing"
Assert-True ($SourceText.Contains("adaptive_sampling_policy")) "adaptive sampling diagnostic marker is missing"
Assert-True ($SourceText.Contains("coverage_report")) "coverage report marker is missing"
Assert-True ($SourceText.Contains("atlas_probe route=f10_v2_runtime_atlas")) "V2 atlas probe diagnostic marker is missing"
Assert-True ($SourceText.Contains("atlas_dump begin route=f10_v2_runtime_atlas")) "V2 atlas diagnostic dump marker is missing"
Assert-True ($SourceText.Contains("atlas_dump kind=function")) "V2 atlas function dump marker is missing"
Assert-True ($SourceText.Contains("atlas_dump kind=property")) "V2 atlas property dump marker is missing"
Assert-True ($SourceText.Contains("atlas_dump kind=related_object")) "V2 atlas related object dump marker is missing"
Assert-True ($SourceText.Contains("atlas_source=")) "atlas source diagnostic marker is missing"
Assert-True ($SourceText.Contains("atlas_probe_ok=")) "atlas probe result marker is missing"
Assert-True ($SourceText.Contains("uv_chart_count=")) "UV chart count marker is missing"
Assert-True ($SourceText.Contains("uv_overlap_ratio=")) "UV overlap ratio marker is missing"
Assert-True ($SourceText.Contains("per_chart_coverage=")) "per-chart coverage marker is missing"
Assert-True ($SourceText.Contains("apply_backend=")) "apply backend marker is missing"
Assert-True ($SourceText.Contains("corrected_deproject_hfov")) "F10 capture FOV diagnostic/source marker is missing"
Assert-True ($SourceText.Contains("job_stage=")) "job stage diagnostic marker is missing"
Assert-True ($SourceText.Contains("phase_ms=")) "phase timing diagnostic marker is missing"
Assert-True ($SourceText.Contains("frame_budget_overrun=")) "frame budget overrun diagnostic marker is missing"
Assert-True ($SourceText.Contains("readback_backend_cached=")) "readback cache diagnostic marker is missing"
Assert-True ($SourceText.Contains("exact_material_source=unavailable")) "exact material source diagnostic marker is missing"
Assert-True ($SourceText.Contains("material_confidence=")) "material confidence diagnostic marker is missing"
Assert-True ($SourceText.Contains("material_source=")) "material source diagnostic marker is missing"
Assert-True ($SourceText.Contains("low_luma_suspect=")) "low-luma diagnostic marker is missing"
Assert-True ($SourceText.Contains("chroma_validation_failed=")) "chroma validation diagnostic marker is missing"
Assert-True ($SourceText.Contains("side_budget_exhausted=")) "side budget diagnostic marker is missing"
Assert-True ($SourceText.Contains("hit_budget_exhausted=")) "screen hit budget diagnostic marker is missing"
Assert-True ($SourceText.Contains("screen_body_front_brush_query")) "front brush query diagnostic marker is missing"
Assert-True ($SourceText.Contains("front_brush_seeds=")) "front brush query result marker is missing"
Assert-True ($SourceText.Contains("material_channels_sent=")) "replicated material channel policy marker is missing"
Assert-True ($SourceText.Contains("replicated_apply=1")) "replicated paint apply marker is missing"
Assert-True ($SourceText.Contains("replicated_strokes_sent=")) "replicated stroke count marker is missing"
Assert-True ($SourceText.Contains("local_echo_strokes=")) "local echo paint marker is missing"
Assert-True ($SourceText.Contains("apply_rpc=")) "server paint RPC marker is missing"
Assert-True ($SourceText.Contains('stroke_server_rpcs{STR("ServerSendPaint"), STR("ServerPaint")}')) "replicated apply does not prefer stroke server paint API"
Assert-True ($SourceText.Contains('local_rpcs{STR("PaintAtUVWithBrush")}')) "local echo still allows brushless PaintAtUV fallback"
Assert-True ($SourceText.Contains("brush_payload=1")) "replicated brush payload marker is missing"
Assert-True ($SourceText.Contains("brush_radius=")) "replicated brush radius marker is missing"
Assert-True ($SourceText.Contains("apply_mode=AlphaBlend")) "replicated paint does not log AlphaBlend apply mode"
Assert-True ($SourceText.Contains("brush_subdivision_level=")) "replicated brush subdivision marker is missing"
Assert-True ($SourceText.Contains("DynamicSubdivisionMinBrushRadius")) "texture-option brush radius probe is missing"
Assert-True ($SourceText.Contains("hidden_background_capture")) "hidden-character background capture marker is missing"
Assert-True ($SourceText.Contains("color_source=hidden_character_capture")) "hidden-character capture color source marker is missing"
Assert-True ($SourceText.Contains("readback_backend=sampled_pixel_tick")) "sampled pixel readback backend marker is missing"
Assert-True ($SourceText.Contains("bulk_readback_used=0")) "bulk readback disable marker is missing"
Assert-True ($SourceText.Contains("sampled_readback_cursor=")) "sampled readback cursor marker is missing"
Assert-True ($SourceText.Contains("sampled_readback_phase_ms=")) "sampled readback timing marker is missing"
Assert-True ($SourceText.Contains("sampled_readback_unavailable_no_apply")) "sampled readback refusal marker is missing"
Assert-True ($SourceText.Contains("stretch_inferred_strokes=")) "curved stretch inferred stroke marker is missing"
Assert-True ($SourceText.Contains("stretch_rejected_seam=")) "curved stretch seam rejection marker is missing"
Assert-True ($SourceText.Contains("stretch_normal_limit=")) "curved stretch normal-limit marker is missing"
Assert-True ($SourceText.Contains("side_backend=screen_space_brush_query_replicated")) "replicated side/back backend marker is missing"
Assert-True ($SourceText.Contains("side_quality_success=")) "side quality success marker is missing"
Assert-True ($SourceText.Contains("side_quality_failed=")) "side quality failure marker is missing"
Assert-True ($SourceText.Contains("front_coverage_ok=")) "front coverage success marker is missing"
Assert-True ($SourceText.Contains("front_coverage_failed=")) "front coverage failure marker is missing"
Assert-True ($SourceText.Contains("vertical_band_hits=")) "front vertical band coverage marker is missing"
Assert-True ($SourceText.Contains("refined_reaches_coarse_bottom=")) "front coarse-bottom coverage marker is missing"
Assert-True ($SourceText.Contains("refined_grid_complete=")) "front refined-grid completion marker is missing"
Assert-True ($SourceText.Contains("alignment_used=1")) "front capture alignment marker is missing"
Assert-True ($SourceText.Contains("projected_delta_avg_px=")) "front projected alignment delta marker is missing"
Assert-True ($SourceText.Contains("capture_resolution_source=viewport_size_required")) "viewport-required capture marker is missing"
Assert-True ($SourceText.Contains("brush_radius_source=density_precision")) "precision brush radius marker is missing"
Assert-True ($SourceText.Contains("material_evidence_probe=")) "material evidence probe marker is missing"
Assert-True ($SourceText.Contains("hidden_background_capture_empty_no_apply")) "hidden capture refusal marker is missing"
Assert-True ($SourceText.Contains("texture_import_used=0")) "texture import disabled marker is missing"
Assert-True ($SourceText.Contains("import_backend=0")) "import backend disabled marker is missing"
Assert-True ($SourceText.Contains("paint_channel_export")) "paint channel export diagnostic marker is missing"
Assert-True ($SourceText.Contains("reflection_api")) "runtime reflection API diagnostic marker is missing"
Assert-True ($SourceText.Contains("target_metallic")) "target metallic diagnostics artifact is missing"
Assert-True ($SourceText.Contains("target_roughness")) "target roughness diagnostics artifact is missing"
Assert-True ($SourceText.Contains("phase_side_ms")) "side phase diagnostics artifact is missing"

$RunPendingStart = $SourceText.IndexOf("auto run_pending_ui_camouflage()")
$StartPipelineStart = $SourceText.IndexOf("auto start_pipeline_job() -> void", $RunPendingStart)
Assert-True ($RunPendingStart -ge 0 -and $StartPipelineStart -gt $RunPendingStart) "run_pending_ui_camouflage section not found"
$RunPendingText = $SourceText.Substring($RunPendingStart, $StartPipelineStart - $RunPendingStart)
Assert-True ($RunPendingText.Contains("start_pipeline_job();")) "F10 path does not start tick pipeline"
Assert-True ($RunPendingText.Contains("advance_pipeline_job();")) "F10 path does not advance tick pipeline"
Assert-True (-not $RunPendingText.Contains("execute_pipeline_once();")) "F10 path still dispatches monolithic execution directly"
Assert-True (-not $RunPendingText.Contains("run_play_deferred_import")) "F10 path still uses deferred import wrapper"
Assert-True (-not $RunPendingText.Contains("start_progressive_paint_job")) "F10 path still starts ProgressivePaintJob"
Assert-True (-not $RunPendingText.Contains("advance_progressive_paint_job")) "F10 path still advances ProgressivePaintJob"

$AdvanceStart = $SourceText.IndexOf("auto advance_pipeline_job() -> void")
$ExecuteOnceStart = $SourceText.IndexOf("auto execute_pipeline_once() -> void", $AdvanceStart)
Assert-True ($AdvanceStart -ge 0 -and $ExecuteOnceStart -gt $AdvanceStart) "advance_pipeline_job section not found"
$AdvanceText = $SourceText.Substring($AdvanceStart, $ExecuteOnceStart - $AdvanceStart)
Assert-True ($AdvanceText.Contains("UiPipelineStage::Preflight")) "F10 pipeline does not advance to V2 preflight"
Assert-True ($AdvanceText.Contains("UiPipelineStage::AtlasProbe")) "F10 pipeline does not run V2 atlas probe"
Assert-True ($AdvanceText.Contains("UiPipelineStage::SurfaceTraceSampling")) "F10 pipeline does not run V2 surface sampling"
Assert-True (-not $AdvanceText.Contains("apply_screen_body_paint_cloak(m_pipeline_job.component")) "F10 advance still calls monolithic apply"
$ResolveTargetStart = $AdvanceText.IndexOf("if (m_pipeline_job.stage == UiPipelineStage::ResolveTarget)")
$RefinedStageStart = $AdvanceText.IndexOf("if (m_pipeline_job.stage == UiPipelineStage::RefinedHit)")
Assert-True ($ResolveTargetStart -ge 0 -and $RefinedStageStart -gt $ResolveTargetStart) "resolve/refined sections not found"
$ResolveTargetText = $AdvanceText.Substring($ResolveTargetStart, $RefinedStageStart - $ResolveTargetStart)
Assert-True ($ResolveTargetText.Contains("probe_v2_runtime_capabilities")) "V2 capability probe is not run before refined hit"
Assert-True ($ResolveTargetText.Contains("probe_v2_runtime_atlas")) "V2 atlas probe is not run before refined hit"
Assert-True ($ResolveTargetText.Contains("continue_to_replicated_apply=1")) "atlas probe no longer continues to replicated apply"
Assert-True (-not $ResolveTargetText.Contains("play v2_runtime_atlas refused")) "atlas probe still refuses before replicated apply"
Assert-True ($AdvanceText.Contains("call_replicated_paint_at_uv")) "F10 route does not call replicated paint API"
Assert-True ($AdvanceText.Contains("MaxReplicatedPaintStrokesPerTick")) "F10 route does not respect game replicated stroke budget"
Assert-True ($AdvanceText.Contains("brush_payload=1")) "F10 route does not apply brush payload strokes"
Assert-True ($AdvanceText.Contains("brush_radius=")) "F10 route does not log adaptive brush radius"
Assert-True ($AdvanceText.Contains("apply_mode=AlphaBlend")) "F10 route still does not use AlphaBlend channel apply mode"
Assert-True ($AdvanceText.Contains("brush_subdivision_level=")) "F10 route does not log brush subdivision payload"
Assert-True ($AdvanceText.Contains("hidden_background_capture")) "F10 route does not capture hidden-character background before apply"
Assert-True ($AdvanceText.Contains("color_source=hidden_character_capture")) "F10 route does not use hidden-character capture RGB"
Assert-True ($AdvanceText.Contains("begin_sampled_scene_capture")) "F10 route does not create sampled scene capture"
Assert-True ($AdvanceText.Contains("readback_backend=sampled_pixel_tick")) "F10 route does not use sampled readback marker"
Assert-True ($AdvanceText.Contains("bulk_readback_used=0")) "F10 route does not disable bulk readback marker"
Assert-True ($AdvanceText.Contains("sampled_readback_cursor=")) "F10 route does not log sampled readback cursor"
Assert-True ($AdvanceText.Contains("side_backend=screen_space_brush_query_replicated")) "F10 route does not connect replicated side/back sampling"
Assert-True ($AdvanceText.Contains("stretch_inferred_strokes=")) "F10 route does not log curved stretch inference"
Assert-True ($AdvanceText.Contains("sampling_order=stratified_grid_y_first")) "F10 refined hit does not use stratified grid traversal"
Assert-True ($AdvanceText.Contains("evaluate_front_coverage")) "F10 route does not evaluate front coverage"
Assert-True ($AdvanceText.Contains("front_coverage_failed")) "F10 route does not log front coverage failure"
Assert-True (-not $AdvanceText.Contains("trace_nearest_background_behind_sample(m_pipeline_job")) "F10 apply still performs per-stroke background trace"
Assert-True (-not $AdvanceText.Contains("exact_material_source=estimated_background_trace")) "F10 route still reports trace RGB as exact material source"
Assert-True (-not $AdvanceText.Contains("ImportChannelFromBytes.screen_body_direct_only")) "F10 route still references local-only texture import success"

Assert-True (-not $SourceText.Contains("pixel_api_after_bulk_unverified")) "unverified pixel fallback marker remains"
Assert-True (-not $SourceText.Contains("aux_surface_copy_v1")) "broken aux_surface_copy_v1 route remains"
Assert-True (-not $SourceText.Contains("screen_silhouette_short_band_v1")) "broken screen_silhouette_short_band_v1 route remains"
Assert-True (-not $SourceText.Contains("uv_local_band_v1")) "broken uv_local_band_v1 route remains"
Assert-True (-not $SourceText.Contains("part_affine_tile")) "broken part_affine_tile route remains"
Assert-True (-not $SourceText.Contains("virtual_multiview_projection_v1")) "broken virtual_multiview_projection_v1 route remains"
Assert-True (-not $SourceText.Contains("world_trace_projection_v1")) "broken world_trace_projection_v1 route remains"
Assert-True (-not $SourceText.Contains("progressive_screen_body")) "progressive_screen_body route remains"
Assert-True (-not $SourceText.Contains("tps_camera_manager_identity")) "tps_camera_manager_identity route remains"
Assert-True (-not $SourceText.Contains("camera_manager_fov_for_capture")) "camera-manager FOV capture regression remains"
Assert-True (-not $SourceText.Contains("pixel_api_batched")) "pixel_api_batched route remains"
Assert-True (-not $SourceText.Contains("auto run_projection_audit")) "projection audit command route remains"
Assert-True (-not $SourceText.Contains("fallback_camo_palette")) "procedural palette fallback remains"
Assert-True (-not $SourceText.Contains("apply_background_palette_import_fallback")) "background palette fallback remains"
Assert-True (-not $SourceText.Contains("apply_view_projection_cloak")) "old view projection route remains"
Assert-True (-not $SourceText.Contains("run_lab_probe")) "old lab probe route remains"
Assert-True (-not $CoreText.Contains("Unreal")) "core contains Unreal dependency"
Assert-True (-not $CoreText.Contains("UObject")) "core contains UObject dependency"
Assert-True (-not $CoreText.Contains("RC::")) "core contains RC dependency"
Assert-True (-not $CoreText.Contains("UE4SS")) "core contains UE4SS dependency"
Assert-True ($CoreText.Contains("capture_trace_chroma_failed_no_paint")) "core chroma quality gate is missing"
Assert-True ($CoreText.Contains("capture_low_dynamic_range_no_paint")) "core low dynamic range quality gate is missing"
Assert-True ($CoreText.Contains("MaterialConfidence")) "core material confidence policy is missing"
Assert-True ($CoreText.Contains("FrameBudget")) "core frame budget policy is missing"
Assert-True ($CoreText.Contains("PipelineJob")) "core pipeline job contract is missing"
Assert-True ($CoreText.Contains("PhaseTiming")) "core phase timing contract is missing"
Assert-True ($CoreText.Contains("CaptureQualityReport")) "core capture quality report is missing"
Assert-True ($CoreText.Contains("PaintRunDiagnostics")) "core paint run diagnostics contract is missing"
Assert-True ($CoreText.Contains("CaptureSizingDecision")) "core capture sizing decision is missing"
Assert-True ($CoreText.Contains("AdaptiveSamplingPolicy")) "core adaptive sampling policy is missing"
Assert-True ($CoreText.Contains("UvCoverageReport")) "core UV coverage report is missing"
Assert-True ($CoreText.Contains("RuntimeAtlasProbeReport")) "core runtime atlas probe contract is missing"
Assert-True ($CoreText.Contains("AtlasTexel")) "core atlas texel contract is missing"
Assert-True ($CoreText.Contains("UvChart")) "core UV chart contract is missing"
Assert-True ($CoreText.Contains("AtlasCoverageReport")) "core atlas coverage contract is missing"
Assert-True ($CoreText.Contains("SurfaceSampleEvidence")) "core surface sample evidence contract is missing"
Assert-True ($CoreText.Contains("ApplyBackendProbe")) "core apply backend contract is missing"
Assert-True ($CoreText.Contains("SampledReadbackTickPlan")) "core sampled readback scheduler contract is missing"
Assert-True ($CoreText.Contains("SurfaceStretchReport")) "core surface stretch contract is missing"
Assert-True ($CoreText.Contains("SideCoverageReport")) "core side coverage contract is missing"
Assert-True ($CoreText.Contains("coverage_failed_no_import")) "core coverage failure policy is missing"
Assert-True ($CoreText.Contains("coverage_failed_side_budget_exhausted_no_import")) "core side coverage failure policy is missing"
Assert-True ($CoreText.Contains("atlas_source_unavailable_no_import")) "core atlas unavailable failure policy is missing"
Assert-True ($CoreText.Contains("coverage_failed_lower_body_no_import")) "core lower-body coverage failure policy is missing"
Assert-True ($CoreText.Contains("apply_backend_unavailable_no_import")) "core apply backend refusal policy is missing"

Write-Host "runtime route checks passed"
